org:
  billing_email: ict@devoptix.nl
  location: Netherlands
  name: DevOptix
  has_organization_projects: true
  has_repository_projects: true
  default_repository_permission: read
  members_can_create_repositories: true
  members_can_create_internal_repositories: false
  members_can_create_private_repositories: true
  members_can_create_public_repositories: true
  members_can_create_pages: true
  members_can_create_public_pages: true
  members_can_create_private_pages: true
  members_can_fork_private_repositories: false
  web_commit_signoff_required: false
members:
  - login: ex0b1t
    role: admin
teams:
  - slug: admin
    name: admin
    description: Admin
    privacy: closed
    members:
      - login: ex0b1t
        role: maintainer
repos:
  - name: .github-private
    visibility: private
    has_issues: true
    has_projects: true
    has_wiki: false
    is_template: false
    members: []
    teams: []
