name: "GitHub GitOps Action"
description: "Configure GitHub Action"
inputs:
  command:
    required: true
    description: |
      Command(s) to run.
      Use a comma separated list to run several commands on the same set of parameters, for instance validate,dry-run
  github-token:
    description: GitHub Token to write comments
    default: ${{ github.token }}
    required: false
runs:
  using: "node16"
  main: "index.js"
