name: 'GitHub GitOps Action'
description: 'Configure GitHub Action'
inputs:
  command:
    required: true
    description: |
      Command to run, for instance dry-run
  organization:
    required: true
    description: |
      GitHub Organization
    default: ${{ github.repository_owner }}
  github-token:
    description: GitHub Token to write comments
    default: ${{ github.token }}
    required: false
runs:
  using: 'node16'
  main: 'dist/index.js'
