name: Pull Request
on:
  pull_request_target:
    branches: [main]
env:
  CARGO_TERM_COLOR: always
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Use Node.js from .nvmrc
        uses: actions/setup-node@v3.7.0
        with:
          node-version-file: ".nvmrc"
          cache: "npm"
      - name: Install Dependencies
        run: npm ci
      - name: Unit tests
        run: npm run test --if-present
  approve:
    name: Approve PR
    runs-on: ubuntu-latest
    needs: [test]
    if: success()
    steps:
      - name: Approve PR
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            await github.rest.pulls.createReview({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
              event: 'APPROVE'
            })
  merge:
    name: Merge Dependabot PR
    runs-on: ubuntu-latest
    needs: [test, approve]
    if: success() && github.actor == 'dependabot[bot]'
    steps:
      - name: Merge PR
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            await github.rest.pulls.merge({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
              merge_method: 'squash'
            })
